language: node_js

node_js:
  - 10.16.0

before_install:
  - npm i -g npm@6.10.0


# see https://docs.travis-ci.com/user/build-stages/
jobs:
  include:
    - stage: test
      name: Unit Tests
      script: npm test
    - name: Bundle Extension
      script: npm run build
